package pojo;
// Generated Oct 5, 2023 4:41:40 PM by Hibernate Tools 4.3.1
import dao.DAOSubQuest;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Subquest generated by hbm2java
 */
@ManagedBean (name="sq")
@Entity
@Table(name="Subquest")
public class Subquest  implements java.io.Serializable {
    @Id 
    private Integer subId;
    @Column
    private Integer biomeId;
    private Biome biome;
    @Column
    private Integer smId;
    private Smallmonster smallmonster;
    private String subName;

    public Subquest() {
    }

    public Integer getBiomeId() {
        return biomeId;
    }

    public void setBiomeId(Integer biomeId) {
        this.biomeId = biomeId;
    }

    public Integer getSmId() {
        return smId;
    }

    public void setSmId(Integer smId) {
        this.smId = smId;
    }

    public Subquest(Biome biome, Smallmonster smallmonster, String subName) {
       this.biome = biome;
       this.smallmonster = smallmonster;
       this.subName = subName;
    }
   
    public Integer getSubId() {
        return this.subId;
    }
    
    public void setSubId(Integer subId) {
        this.subId = subId;
    }
    public Biome getBiome() {
        return this.biome;
    }
    
    public void setBiome(Biome biome) {
        this.biome = biome;
    }
    public Smallmonster getSmallmonster() {
        return this.smallmonster;
    }
    
    public void setSmallmonster(Smallmonster smallmonster) {
        this.smallmonster = smallmonster;
    }
    public String getSubName() {
        return this.subName;
    }
    
    public void setSubName(String subName) {
        this.subName = subName;     
    }   

     public List<Subquest> getbyid() {
        DAOSubQuest sqdao = new DAOSubQuest();
        List<Subquest> squest = sqdao.getbyID(subId);
        biome = squest.get(0).biome;
        smallmonster = squest.get(0).smallmonster;
        subName= squest.get(0).subName;
        return squest;
    }

    public List<Subquest> getAllRecords() {
        DAOSubQuest sqdao = new DAOSubQuest();
        List<Subquest> squest = sqdao.showSQ();
        return squest;
    }
}


